#!/bin/bash

user_fetch(){
if grep ^simple_fetch $BUILDME_FILE >/dev/null 2>&1; then
	source $BUILDME_FILE
	if type simple_fetch > /dev/null 2>&1; then
		simple_fetch || return 1
	fi
fi
}


fetch_files(){

for CPV in ${USERLIST_TO_INSTALL[@]}; do
	get_variables $CPV

	BUILDME_FILE=$BUILDME_DIR/$CATEGORY/$PACKAGE/$PACKAGE-$VERSION$raw_patch.buildme

	if [[ $(cat $BUILDME_FILE) =~ $regexSRC_URL ]]; then
		while read -r LINE; do
			while [[ $LINE =~ \$(\{([a-zA-Z_][a-zA-Z_0-9]*)\})(.*) ]]; do
				NEW_LINE+="${LINE%"$BASH_REMATCH"}${!BASH_REMATCH[2]}"
				LINE=${BASH_REMATCH[3]}
			done
			SRC_URL="$NEW_LINE$LINE"
		done < <(eval echo ${BASH_REMATCH[2]})
	else
		echo -e "\e[31mSRC_URL is no difended in $BUILDME_FILE\e[0m"
		return 1
	fi

	unset LINE NEW_LINE

	if [[ $(cat $BUILDME_FILE) =~ $regexMD5_SUM ]]; then
		MD5_SUM="${BASH_REMATCH[2]}"
	else
		echo -e "\e[31mMD5_SUM is no difended in $BUILDME_FILE\e[0m"
		return 1
	fi

	if [[ $(if_renamed_source) != true ]]; then
		FAN=$(echo "$SRC_URL" | sed -r 's#.*\/([-_a-z0-9.]*)#\1#')
	else
		FAN=$(echo "$SRC_URL" | tr -s [:space:] ' ' | cut -d ' ' -f3)
	fi

	if [ -f "$DISTDIR/$FAN" ]; then
		echo -e "\e[96mFile $FAN available\e[0m"
		FILE_SUM=$(md5sum "$DISTDIR/$FAN" | cut -d ' ' -f 1)
		ORIG_SUM=$MD5_SUM

		if [ "$ORIG_SUM" != "$FILE_SUM" ]; then
			echo -e "\e[31mControl sum not corect. Trying to redownload $FAN\e[0m"

			if [[ $(if_renamed_source) != true ]]; then
				wget "$SRC_URL" --continue --directory-prefix="$DISTDIR" || return 1
			else
				FILE_NAME=$(echo "$SRC_URL" | tr -s [:space:] ' ' | cut -d ' ' -f3)
				SRC_URL_RENAMED=$(echo "$SRC_URL" | tr -s [:space:] ' ' | cut -d ' ' -f1)
				wget "$SRC_URL_RENAMED" --continue --output-document="$DISTDIR/$FILE_NAME" || return 1
			fi

			FILE_SUM=$(md5sum "$DISTDIR/$FAN" | cut -d ' ' -f 1)
			if [ "$ORIG_SUM" != "$FILE_SUM" ]; then
				echo -e "\e[31mControl sum not corect\e[0m"
				return 1
			fi
		else
			echo -e "\e[96mControl sum correct\e[0m"
		fi

	else
		echo -e "\e[96mFile $FAN is NOT available. Trying to download\e[0m"

		if [[ $(if_renamed_source) != "true" ]]; then
			wget "$SRC_URL" --continue --directory-prefix="$DISTDIR" || return 1
		else
			FILE_NAME=$(echo "$SRC_URL" | tr -s [:space:] ' ' | cut -d ' ' -f3)
			SRC_URL_RENAMED=$(echo "$SRC_URL" | tr -s [:space:] ' ' | cut -d ' ' -f1)
			wget "$SRC_URL_RENAMED" --continue --output-document="$DISTDIR/$FILE_NAME" || return 1
		fi

		FILE_SUM=$(md5sum "$DISTDIR/$FAN" | cut -d ' ' -f 1)
		ORIG_SUM="$MD5_SUM"

		if [ "$ORIG_SUM" != "$FILE_SUM" ]; then
			echo -e "\e[31mControl sum not corect\e[0m"
			return 1
		fi
	fi

	#debug
	debug_message "\e[96mFile have  $FILE_SUM\e[0m"
	debug_message "\e[96mCorrect is $ORIG_SUM\e[0m"

	# to run on fetch phase from buildme
	user_fetch || { echo -e "\e[31m  * user_fetch failed\e[0m" && return 1; }


	unset FILE_SUM ORIG_SUM SRC_URL SRC_URL_RENAMED FILE_NAME
	unset CATEGORY PACKAGE VERSION category package raw_package ver_modif ver_sep version

done
}

source /usr/lib/simple/libsimple
source $SIMPLEBUILD_DIR/bashrc
cd $SIMPLEBUILD_DIR

fetch_files || { echo -e "\e[31m  * fetch_files failed\e[0m" && exit 1; }
