#!/bin/bash

install_files(){
if ! type simple_install > /dev/null 2>&1
	then echo -e "\e[96msimple_install() is not definded in buildme file. Runing default\e[0m"

	BROOT=$BROOT sandbox make DESTDIR=${D} install
else
	echo -e "\e[96mRun simple_install() from buildme file\e[0m"
	simple_install || return 1
fi
}

strip_files(){
cd "$D" || return 1
echo -n -e "\e[96mStripping libraries  \e[0m"
strip --strip-debug {,usr/}lib{,64,32,x32}/* 2>/dev/null
echo "Ok"

echo -n -e "\e[96mStripping binaries  \e[0m"
strip --strip-unneeded {,usr/}{,s}bin/* 2>/dev/null
echo "Ok"
}

setup_env(){
CPV=$1
source /usr/lib/simple/libsimple
source /var/tmp/simple/bashrc
cd $SIMPLEBUILD_DIR
get_variables $CPV

BROOT="$SIMPLEBUILD_DIR/$CATEGORY/$PACKAGE-$VERSION$raw_patch"
source "$BROOT/varlog/variables"
source "$BUILDME_FILE"
cd "$B"
export CATEGORY PACKAGE VERSION BROOT S B D
}

setup_env $1
install_files
strip_files
